name: Compilar AutoLevelGen

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar mod (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/cli/.github/actions/install@v3
      - uses: geode-sdk/sdk/.github/actions/setup@v3
      - name: Compilar
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: AutoLevelGen
          path: build/Release/*.geode
